name: eslint
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  test-binaries:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.13.1
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
      - run: npm i
      - run: npm run lint
