name: Release tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-docker-images:
    name: Create and push docker images
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.14.2
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.2
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
      - uses: docker-practice/actions-setup-docker@master
      - run: npm i
      - run: npm run build-docker-images