# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: release
on:
  # Trigger the workflow on push
  # but only for the master branch
  push:
    tags:
      - "*"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  create-release:
    name: Create Github Release
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: "Join the community at https://h1emu.com/"
          draft: false
          prerelease: false

  build-binaries:
    name: Create Binaries
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.2.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.2.0
      - run: npm ci
      - run: npm i -g pkg@5.2.1
      - run: pkg -t node16-win-x64 ./bin/2015/loginServer.js --output ./bin/loginServer-${{ github.ref }}.exe
      - run: pkg -t node16-win-x64 ./bin/2015/zoneServer.js --output ./bin/zoneServer-${{ github.ref }}.exe
      - run: pkg -t node16-win-x64 ./bin/2015/h1emuServer.js --output ./bin/h1emuServer-${{ github.ref }}.exe
      - run: pkg -t node16-win-x64 ./bin/2016/loginServer.js --output ./bin/loginServer-2016-${{ github.ref }}.exe
      - run: pkg -t node16-win-x64 ./bin/2016/zoneServer.js --output ./bin/zoneServer-2016-${{ github.ref }}.exe
      - run: pkg -t node16-win-x64 ./bin/2016/h1emuServer.js --output ./bin/h1emuServer-2016-${{ github.ref }}.exe
      - name: Upload h1emuServer to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./bin/h1emuServer-${{ github.ref }}.exe
          asset_name: h1emuServer-${{ github.ref }}.exe
          tag: ${{ github.ref }}
      - name: Upload zoneServer to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./bin/zoneServer-${{ github.ref }}.exe
          asset_name: zoneServer-${{ github.ref }}.exe
          tag: ${{ github.ref }}
      - name: Upload loginServer to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./bin/loginServer-${{ github.ref }}.exe
          asset_name: loginServer-${{ github.ref }}.exe
          tag: ${{ github.ref }}
      - name: Upload h1emuServer-2016 to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./bin/h1emuServer-2016-${{ github.ref }}.exe
          asset_name: h1emuServer-2016-${{ github.ref }}.exe
          tag: ${{ github.ref }}
      - name: Upload zoneServer-2016 to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./bin/zoneServer-2016-${{ github.ref }}.exe
          asset_name: zoneServer-2016-${{ github.ref }}.exe
          tag: ${{ github.ref }}
      - name: Upload loginServer-2016 to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./bin/loginServer-2016-${{ github.ref }}.exe
          asset_name: loginServer-2016-${{ github.ref }}.exe
          tag: ${{ github.ref }}
