name: test runtime
on:
  push:
    branches: [master]
  pull_request:
    branches: [master, dev]
jobs:
  test-linux:
    runs-on: ubuntu-latest
    env:
     FORCE_REDUCE_CPU_USAGE: "true"
    strategy:
      matrix:
        node-version: [16.14.2, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm test
  test-win:
    runs-on: windows-latest
    env:
     FORCE_REDUCE_CPU_USAGE: "true"
    strategy:
      matrix:
        node-version: [16.14.2, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm test
